blog/urls.py
from django.urls import path, include
from . import views

app_name = 'blog'

urlpatterns = [
	path('', views.home, name='home'),

]

file_converter/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'file_converter'

urlpatterns = [
    path('', views.file_list, name='file_list'),
    path('admin/', admin.site.urls),
    path('files/', views.file_list, name='file_list'),
    path('files/upload_file/', views.upload_file, name='upload_file'),
    path('files/<int:pk>/', views.delete_file, name='delete_file'),
]

lucidpy_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main_app.urls')),
    path('apps/', include('file_converter.urls')),
    path('blog/', include('blog.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

file_converter/models.py
from django.db import models


# Create your models here.
class File(models.Model):
	name = models.CharField(max_length=100)
	data_description = models.CharField(max_length=200)
	file = models.FileField(upload_to='files/')

	def __str__(self):
		return self.name

	def delete(self, *args, **kwargs):
		self.file.delete()
		super().delete(*args, **kwargs)

file_converter/forms.py
from django import forms
from .models import File

class FileUploadForm(forms.ModelForm):
	class Meta:
		model = File
		fields = ('name', 'data_description', 'file')

file_converter/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.core.files.storage import FileSystemStorage
from django.contrib import messages
from .forms import FileUploadForm
from .models import File

# Create your views here.
def upload(request):
	context = {}
	if request.method =='POST':
		uploaded_file = request.FILES['document']
		fs = FileSystemStorage()
		saved_name = fs.save(uploaded_file.name, uploaded_file)
		file_name = uploaded_file.name
		file_size = uploaded_file.size
		context['saved_file_url'] = fs.url(saved_name)
		messages.success(request, f'A file {file_name} was loaded successfuly!')
		messages.success(request, f'File size - {file_size} bytes')
	return render(request=request, 
				  template_name='file_converter/file_upload_form.html',
				  context=context) 


def file_list(request):
	files = File.objects.all()
	return render(request=request, 
				  template_name='file_converter/file_list.html',
				  context={'files': files})


def upload_file(request):
	if request.method == 'POST':
		form = FileUploadForm(request.POST, request.FILES)
		if form.is_valid():
			form.save()
			return redirect('file_converter:file_list')
	else:
		form = FileUploadForm()
	return render(request=request, 
				  template_name='file_converter/file_upload.html',
				  context={'form': form})

def delete_file(request, pk):
	if request.method == 'POST':
		file = File.objects.get(pk=pk)
		file_name = file.name
		file.delete()
		messages.success(request, f'File \"{file_name}\" was deleted!')
	return redirect('file_converter:file_list')

	

file_converter/templates/file_converter/file_list.html
{% extends 'main_app/main_theme.html' %}

{% block content %}
<p>
	<a href="{% url 'file_converter:upload_file' %}" class="btn btn-primary">Upload</a>
</p>

<table class="table mb-0">
	<thead>
		<tr>
			<th>File Name</th>
			<th>Data Description</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		{% for data_file in files %}
			<tr>
				<td>{{ data_file.name }}</td>
				<td>{{ data_file.data_description }}</td>
				<td>
					<a href="{{ data_file.file.url }}" class="btn btn-primary btn-sm" target="_blank">Download</a>
				</td>					
				<td>
	
					<a style="background-color: red; color: white" class="waves-effect waves-light btn modal-trigger" href="#delete_confirmation_modal">Delete</a>
					</div>

					<div id="delete_confirmation_modal" class="modal">
						<div class="modal-content">
							<h4>Are you sure you want to delete this file?</h4>
						</div>

						<div class="modal-footer">
							<form method="post" action="{% url 'file_converter:delete_file' data_file.pk %}">
								{% csrf_token %}
								<button type="submit" class="modal-close waves-effect waves-green btn-flat">Delete anyway</button>
								<a href="#!" class="modal-close waves-effect waves-green btn-flat">Cancel</a>
							</form>
						</div>
					</div>

					<div id="delete_form">
					</div>
				</td>
			</tr>
		{% endfor %}
	</tbody>
</table>
{% endblock %}

file_converter/templates/file_converter/file_upload.html
{% extends 'main_app/main_theme.html' %}
{% load crispy_forms_tags %}

{% block content %}
	<h2>Upload File</h2>
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form|crispy }}
		<br>
		<button type="submit" class="btn btn_primary">Upload File</button>
	</form>
{% endblock %}

file_converter/templates/file_converter/file_upload_form.html
{% extends 'main_app/main_theme.html' %}

{% block content %}
	<h2>Upload File</h2>
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<input type="file" name="document">
		<button type="submit">Upload File</button>
	</form>
	{% if saved_file_url %}
		<p>Uploaded file: <a href="{{saved_file_url}}">{{saved_file_url}}</a></p>
	{% endif %}

{% endblock %}

file_converter/templates/file_converter/main_theme.html
<head>
	{% load static %}
    <link rel="shortcut icon" href="{% static 'main_app/images/favicon.ico' %}" />
 	  <link href="{% static 'tinymce/css/prism.css' %}" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>  
</head>

<body>
  <nav>
    <div class="nav-wrapper">
      <a href="/" class="brand-logo">Lucid <strong>PY</strong>thon</a>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
      	{% include 'main_app/includes/navbar_items.html' %}
      </ul>
    </div>
  </nav>
	  
  <ul class="sidenav" id="mobile-demo">
    {% include 'main_app/includes/navbar_items.html' %}
  </ul>
  {% include 'main_app/includes/messaging.html' %}
  <div class="container">
  	{% block content %}
  	{% endblock %}
  </div>
</body>

<script src="{% static 'tinymce/js/prism.js' %}"></script>
<script>M.AutoInit();</script>